version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.3-node-browsers
    steps:
      - checkout
      - restore_cache: # the version on this cache changes rarely, only when a significant setting breaks the cache
          key:
            dotcache-cache-{{checksum ".circleci/config.yml" }}-{{ checksum
            "package.json" }}
      - run:
          name: Setup Dependencies
          command: yarn install --frozen-lockfile
      - save_cache: # special step to save the dependency cache
          key:
            dotcache-cache-{{checksum ".circleci/config.yml" }}-{{ checksum
            "package.json" }}
          paths:
            - ~/.cache
      - run: # run tests
          name: Run Test and Coverage
          command: |
            yarn test:coverage
      - run:
          name: Build static files for serving
          command: |
            yarn build
